version: "3"

services:
  prometheus-eureka:
    image: cqx/prometheus-eureka
    container_name: prometheus-eureka
    networks:
    - cqx-net
    environment:
      JAVA_OPTS: -Xmx256m -Xms256m -Xss512k -Djava.security.egd=file:/dev/./urandom
      TZ: Asia/Shanghai
    ports:
    - 9091:9091

networks:
  cqx-net:
    external: true