global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '82803852@qq.com'
  smtp_auth_username: '82803852@qq.com'
  smtp_auth_password: '授权码'
  smtp_require_tls: false
route:
  # 默认配置
  group_by: ['alertname', 'instance']  #分组规则 根据告警名称与实例分组
  group_wait: 10s          # 当一个新的报警分组被创建后，需要等待至少group_wait时间来初始化通知，这种方式可以确保您能有足够的时间为同一分组来获取多个警报，然后一起触发这个报警信息。
  group_interval: 5m      # 当第一个报警发送后，等待'group_interval'时间来发送新的一组报警信息。
  repeat_interval: 60m      # 如果一个报警信息已经发送成功了，等待'repeat_interval'时间来重新发送他们
  receiver: 'web.hook'
  routes:
  - receiver: 'email'
    match:
      app: "MONITOR-ADMIN" #app是这个的 则用当前route处理即发送email
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'email'
  email_configs:
  - to: 'chenqixing@zailingtech.com'
    send_resolved: true