# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name:     'eureka-sd'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - /Users/cqx/Projects/brooklyn/eureka-sd.json
        refresh_interval: 10s