version: "3"

services:
  prometheus:
    image: cqx/prometheus:latest
    container_name: cqx-prometheus
    networks:
    - cqx-net
    environment:
      NODE_TYPE: MASTER
    volumes:
      - ./conf:/prometheus/conf
    ports:
      - 9090:9090

networks:
  cqx-net:
    external: true


